"""Pydantic schemas for request/response validation."""
from app.schemas.user import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserPasswordUpdate,
    UserResponse,
    UserPublicResponse,
    Token,
    TokenPayload,
    RefreshTokenRequest,
    LoginRequest,
)
from app.schemas.property import (
    LocationInput,
    LocationOutput,
    PropertyImageBase,
    PropertyImageCreate,
    PropertyImageResponse,
    PropertyBase,
    PropertyCreate,
    PropertyUpdate,
    PropertyResponse,
    PropertyListResponse,
    PropertySearchParams,
)
from app.schemas.application import (
    ReferenceInfo,
    DocumentInfo,
    ApplicationBase,
    ApplicationCreate,
    ApplicationUpdate,
    ApplicationStatusUpdate,
    ApplicationWithdraw,
    ApplicationResponse,
    ApplicationListResponse,
    ApplicationListParams,
)

__all__ = [
    # User schemas
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserPasswordUpdate",
    "UserResponse",
    "UserPublicResponse",
    "Token",
    "TokenPayload",
    "RefreshTokenRequest",
    "LoginRequest",
    # Property schemas
    "LocationInput",
    "LocationOutput",
    "PropertyImageBase",
    "PropertyImageCreate",
    "PropertyImageResponse",
    "PropertyBase",
    "PropertyCreate",
    "PropertyUpdate",
    "PropertyResponse",
    "PropertyListResponse",
    "PropertySearchParams",
    # Application schemas
    "ReferenceInfo",
    "DocumentInfo",
    "ApplicationBase",
    "ApplicationCreate",
    "ApplicationUpdate",
    "ApplicationStatusUpdate",
    "ApplicationWithdraw",
    "ApplicationResponse",
    "ApplicationListResponse",
    "ApplicationListParams",
]
